In [2]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
print(type(a))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [3]:
len(a)

10

In [7]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(type(b))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [9]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
c.ndim


2

In [13]:
b.ndim

2

In [14]:
a.ndim

1

In [15]:
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [16]:
d.ndim

3

In [17]:
e=np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(e)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [18]:
e.ndim

4

In [19]:
e.shape

(1, 1, 3, 3)

- The outermost dimension has length 1.
- The second dimension has length 1.
- The third dimension has length 3.
- The fourth dimension has length 3.
- So, e represents a single 3x3 matrix wrapped inside two layers of singleton dimensions. Each matrix contains integers from 1 to 9 arranged in a 3x3 grid.

In [20]:
e.dtype

dtype('int32')

In [11]:
arr=np.array([10,20,30,40])
print(arr[:2])

[10 20]


In [15]:
arr=np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0:2,0:2])


[[10 20]
 [50 60]]


In [34]:
na=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(na[2,0:2])

print('*'*8)
print(na[2,0:2])

print(np.size(na))
print(np.shape(na))


[ 9 10]
********
[ 9 10]
12
(3, 4)


In [35]:
na.dtype

dtype('int32')

### array functions

# shape



In [36]:
np.shape(na)

(3, 4)

In [37]:
na.ndim

2

In [38]:
na.size

12

In [39]:
na.dtype

dtype('int32')

In [40]:
na.astype(str)

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8'],
       ['9', '10', '11', '12']], dtype='<U11')

In [41]:
len(na)

3

### Mathematical operations in numpy


In [1]:
import array as arr

a=arr.array('u',['a','b','c'])
print(a)


array('u', 'abc')


In [10]:
import numpy as np 
a=np.array([1,2,3,4,5])
print(a.ndim)

1


In [11]:
b=np.array([[1,2,3],[4,5,6]])
print(b.ndim)

2


In [16]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c.ndim)
print(c.shape)

3
(1, 3, 3)


In [18]:
d=np.array([[[[1,2,3],[4,5,6],[7,8,9],[23,52,61]]]])
print(d.ndim)
print(d.shape)

4
(1, 1, 4, 3)


In [20]:
e=np.ones((3,2,3))
print(e)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [23]:
f=np.zeros((3,2,3),dtype='int')
print(f)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [26]:
g=np.random.rand(3,2,2)
print(g)

[[[0.29395671 0.88605193]
  [0.7839681  0.25133828]]

 [[0.02542467 0.34473981]
  [0.23568643 0.25122642]]

 [[0.31269779 0.75590489]
  [0.32749703 0.30196888]]]


In [1]:
import numpy as np

In [4]:
lst=[1,2,3,4,5,6]
arr1=np.array(lst)
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [10]:
b.shape

(1, 3, 4)

In [11]:
b.size

12

In [12]:
b.reshape(4,3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
b.shape 

(1, 3, 4)

In [17]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
arr_3d.shape

(2, 2, 2)

In [32]:
r1=np.array([[1,2,3],[4,5,6],[7,8,9]])
r1 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
r1.shape

(3, 3)

In [34]:
r2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
r2.shape

(1, 3, 3)

In [35]:
r3=np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
r3.shape

(3, 1, 3)

In [37]:
# indexing

arr=np.array([1,2,3,4,5,6,7,8,9])

In [38]:
arr[3]

4

In [39]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
arr1.shape


(3, 4)

In [44]:
ac=np.arange(1,10)
ac

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
ra=np.random.rand(2,4)

In [46]:
ra

array([[0.66892859, 0.0561386 , 0.24025477, 0.86211045],
       [0.58246353, 0.54268307, 0.59051422, 0.86910485]])

In [49]:
ra1=np.random.random((2,4))
ra1

array([[0.25870342, 0.45914641, 0.40879899, 0.1845028 ],
       [0.04689956, 0.49260816, 0.66309556, 0.87016767]])

In [51]:
ra1=np.random.random((2,4))
ra1

array([[0.07648117, 0.88483821, 0.35691892, 0.49631863],
       [0.08928792, 0.61383575, 0.39455137, 0.95733629]])

In [53]:
z=np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
arr1[::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
arr1[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
arr[1:,]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
import numpy as np 


In [2]:
a1=np.array([[1,2,3,4]])
a1.ndim

2

In [12]:
a2=np.array([[[4,5,6]]])
a2.ndim

3

In [11]:
a3=np.array([[[4,5,6]]],ndmin=10)
a3

array([[[[[[[[[[4, 5, 6]]]]]]]]]])

In [17]:
arr=np.array([[10,20,40],[50,60,70]])
arr

array([[10, 20, 40],
       [50, 60, 70]])

In [18]:
# type conversion
arr.dtype

dtype('int32')

In [23]:
arr=np.array(arr,dtype='float')
arr.dtype

dtype('float64')

In [25]:
arr=arr.astype(int)
arr.dtype

dtype('int32')

In [28]:
arr.shape

(2, 3)

In [29]:
arr.size

6

In [30]:
arr.itemsize

4

In [33]:
arr.min()

10

In [34]:
arr.max()

70

In [35]:
arr.sum()

250

In [36]:
arr

array([[10, 20, 40],
       [50, 60, 70]])

In [37]:
# adding elements on columns(0)
arr.sum(axis=0)


array([ 60,  80, 110])

In [38]:
# adding elements on rows(1)
arr.sum(axis=1)

array([ 70, 180])

In [39]:
# get how many bytes of memory array uses
arr.itemsize *arr.size

24

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a.dtype

dtype('int32')

In [6]:
b=np.array([[1,2,3],
    [4,5,6],
    [7,8,9]])
b.dtype
b.ndim


2

In [9]:
c=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
c.dtype
c.ndim

2

In [12]:
np.zeros((3,3),dtype='float')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,3),dtype='int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])